### ISSUE TITLE
HAA split file problem

### ISSUE THREAD

**Issue by acewjh** [Sausage-SONG/Few-shot-action-recognition#2]
Hello, I notice the HAA dataset has 500 classes, while the split file is 310/156. Is there a problem in this split file?

**Comment by Sausage-SONG** [comment]
Hi Jiahao,

When we started this project, we only tried to use those classes that are relatively human-centric. We applied skeleton detection on all the classes and left alone those with an extremely low score.

Also, I just noticed that HAA released its v1.1. I believe we were using v1.0 in this project.

**Comment by Sausage-SONG** [comment]
And thanks for your interest. The trained models will be uploaded later as I am having a poor internet connection in a hotel at this moment. Also, I cleaned the codes without much testing, I will keep working on this repo.

**Comment by acewjh** [comment]
Thanks for the reply, looking forward to new progress!
